[0m17:29:14.813246 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF6CB2A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF7CEC190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF7E0FC50>]}


============================== 17:29:14.825338 | 4a2ece78-406d-4086-81c8-48862fd9930c ==============================
[0m17:29:14.825338 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:29:14.826772 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\talla\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:29:43.447153 [debug] [MainThread]: Starter project path: C:\Users\talla\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\include\starter_project
[0m17:29:43.521490 [info ] [MainThread]: 
Your new dbt project "customers_transformation" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:29:43.524042 [info ] [MainThread]: Setting up your profile.
[0m17:30:46.022867 [info ] [MainThread]: Profile customers_transformation written to C:\Users\talla\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:30:46.030508 [debug] [MainThread]: Command `dbt init` succeeded at 17:30:46.029648 after 91.59 seconds
[0m17:30:46.032276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF7EAED70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF7ECC950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF7E7B8A0>]}
[0m17:30:46.038534 [debug] [MainThread]: Flushing usage events
[0m17:30:46.879797 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:31:06.035950 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C458982A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C4599BC190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C459AE3C50>]}


============================== 17:31:06.048908 | a7e60fec-2197-4e4c-8fc0-457a43231182 ==============================
[0m17:31:06.048908 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:31:06.050980 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\talla\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:31:06.120104 [info ] [MainThread]: dbt version: 1.9.4
[0m17:31:06.122094 [info ] [MainThread]: python version: 3.13.3
[0m17:31:06.123587 [info ] [MainThread]: python path: C:\Users\talla\AppData\Local\Programs\Python\Python313\python.exe
[0m17:31:06.125171 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m17:31:06.329339 [info ] [MainThread]: Using profiles dir at C:\Users\talla\.dbt
[0m17:31:06.331381 [info ] [MainThread]: Using profiles.yml file at C:\Users\talla\.dbt\profiles.yml
[0m17:31:06.333057 [info ] [MainThread]: Using dbt_project.yml file at E:\big_data_pipline\data_transformation\dbt_project.yml
[0m17:31:06.334817 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m17:31:06.338303 [debug] [MainThread]: Command `dbt debug` failed at 17:31:06.337908 after 0.67 seconds
[0m17:31:06.340194 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C459B7FA80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C459CD9C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C459CB05A0>]}
[0m17:31:06.341404 [debug] [MainThread]: Flushing usage events
[0m17:31:07.009505 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:34:16.405523 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002611FC72A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026120CAC190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026120DD7C50>]}


============================== 17:34:16.421468 | b782e011-71d3-4c73-8982-55108b0ba938 ==============================
[0m17:34:16.421468 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:34:16.423488 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\talla\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:34:16.425121 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\big_data_pipline\data_transformation\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:34:16.428164 [debug] [MainThread]: Command `dbt run` failed at 17:34:16.427811 after 0.44 seconds
[0m17:34:16.429181 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026120CCB230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026120E28710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026120E3C490>]}
[0m17:34:16.430311 [debug] [MainThread]: Flushing usage events
[0m17:34:17.216726 [debug] [MainThread]: An error was encountered while trying to flush usage events
