[0m20:27:47.056363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C230B42A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C231B68190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C231C97C50>]}


============================== 20:27:47.071257 | f62382ef-9001-417e-966c-ecb5e93a6ca7 ==============================
[0m20:27:47.071257 [info ] [MainThread]: Running with dbt=1.9.4
[0m20:27:47.073628 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\talla\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:27:47.076992 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\big_data_pipline\docker\kafka\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:27:47.082400 [debug] [MainThread]: Command `dbt run` failed at 20:27:47.081886 after 0.35 seconds
[0m20:27:47.084111 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C231B8B230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C231CE8710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C231CFC490>]}
[0m20:27:47.086508 [debug] [MainThread]: Flushing usage events
[0m20:27:48.062523 [debug] [MainThread]: An error was encountered while trying to flush usage events
